name: CI Checks

on: [push]

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run autoformat
        run: uv run ./run_in_all_packages.sh "./run_autoformat.sh"

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK BLAS, and OSMESA
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: |
          uv run ./run_in_all_packages.sh "pytest . --pylint -m pylint --pylint-rcfile=.pylintrc"

  static-type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Mypy
        run: |
          uv run ./run_in_all_packages.sh "mypy ."

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install LAPACK BLAS, and OSMESA
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev libosmesa6-dev libgl1 libglx-mesa0
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Pytest
        env:
          MUJOCO_GL: "osmesa"
          PYOPENGL_PLATFORM: ""
        run: |
          uv run ./run_in_all_packages.sh "pytest tests/"
